---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alloy
  namespace: monitoring-system
spec:
  hostnames:
  - alloy.docker.localhost
  parentRefs:
  - name: traefik-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - name: alloy
      port: 12345
    matches:
    - path:
        type: PathPrefix
        value: /
