secrets:
  existingSecret:
    name: codelab-minio-env

tenant:
  name: codelab
  configuration:
    name: codelab-minio-env
  pools:
  - name: pool-10gb
    # https://github.com/minio/operator/pull/1828
    # currrent not work in minio tenant 5.0.11
    reclaimStorage: true
    servers: 1
    volumesPerServer: 1
    size: 10Gi

  features:
    bucketDNS: false
    domains: { }
    enableSFTP: false
  
  exposeServices:
    minio: false
    console: false

  buckets:
  - name: mimir-blocks
  - name: mimir-ruler
  - name: mimir-alertmanager
  - name: loki-data
  - name: loki-ruler
  - name: tempo-data
  - name: pyroscope-data
  
  # Each secret should specify the ``CONSOLE_ACCESS_KEY`` and ``CONSOLE_SECRET_KEY`` as the access key and secret key for that user.
  users:
  - name: user-lgtmp