analytics:
  reporting_enabled: false

# https://grafana.com/docs/pyroscope/latest/configure-server/configure-disk-storage/#configure-pyroscope-disk-storage
pyroscopedb:
  max_block_duration: 5m

# https://grafana.com/docs/pyroscope/latest/configure-server/reference-configuration-parameters/#use-environment-variables-in-the-configuration
storage:
  backend: s3
  s3:
    bucket_name: pyroscope-data
    endpoint: ${PYROSCOPE_STORAGE_S3_ENDPOINT:-minio.minio-system.svc:443}
    access_key_id: ${PYROSCOPE_STORAGE_S3_ACCESS_KEY_ID:-lgtmp}
    secret_access_key: ${PYROSCOPE_STORAGE_S3_SECRET_ACCESS_KEY:-supersecret}
    insecure: ${PYROSCOPE_STORAGE_S3_INSECURE:-false}
    http:
      insecure_skip_verify: true
