---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: codelab-console
  namespace: minio-system
spec:
  hostnames:
  - codelab-console.docker.localhost
  parentRefs:
  - name: traefik-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - name: codelab-console
      port: 9443
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: tls-upstream-codelab-console
  namespace: minio-system
spec:
  targetRefs:
    - kind: Service
      name: codelab-console
      group: ""
  validation:
    hostname: codelab-console.docker.localhost
    caCertificateRefs:
      - kind: Secret
        name: minio-operator-ca-certificate
        group: ""