# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: false

# -usage-stats.enabled=false
usage_stats:
  enabled: false

server:
  http_listen_port: 8080
  grpc_listen_port: 9095
  log_level: info

common:
  storage:
    backend: s3
    s3:
      endpoint:          ${MIMIR_S3_ENDPOINT:minio:9000}
      access_key_id:     ${MIMIR_S3_ACCESS_KEY_ID:lgtmp}
      secret_access_key: ${MIMIR_S3_SECRET_ACCESS_KEY:supersecret}
      insecure:          ${MIMIR_S3_INSECURE:true}
      http:
        insecure_skip_verify: true

alertmanager:
  data_dir: /data/alertmanager
  enable_api: true
  external_url: /alertmanager
  fallback_config_file: /etc/mimir/alertmanager-fallback-config.yaml
alertmanager_storage:
  s3:
    bucket_name: mimir-alertmanager

blocks_storage:
  s3:
    bucket_name: mimir-blocks
  tsdb:
    dir: /data/ingester

frontend:
  parallelize_shardable_queries: true
  scheduler_address: query-scheduler:9095
frontend_worker:
  grpc_client_config:
    max_send_msg_size: 419430400
  scheduler_address: query-scheduler:9095

memberlist:
  join_members: [ mimir-memberlist:7946 ]

ruler:
  rule_path: /data/rules
  enable_api: true
  alertmanager_url: http://alertmanager:8080/alertmanager
ruler_storage:
  s3:
    bucket_name: mimir-ruler

runtime_config:
  file: /etc/mimir/runtime.yaml

query_scheduler:
  max_outstanding_requests_per_tenant: 800

limits:
  native_histograms_ingestion_enabled: true
