apiVersion: v2
appVersion: v0.37.4
dependencies:
- condition: crds.create
  name: crds
  repository: ""
  version: 0.0.0
description: Grafana Agent
name: grafana-agent
type: application
version: 0.27.2
